# syntax=docker/dockerfile:1.4

ARG NODE_VERSION=20.15

# ===================================
#       PHASE 1 - DEPENDENCIES
# ===================================
FROM reg.ult.vn/template/bun-api:v0-7-3-a AS deps
WORKDIR /app

# Copy package files and remove version
COPY package.json prisma ./

RUN bun install

# ===================================
#       PHASE 2 - runner
# ===================================
FROM reg.ult.vn/template/bun-api-runner:v0-7-3-b AS runner

WORKDIR /usr/app

# Copy dependencies from deps stage
COPY --chown=runner:nodejs --from=deps /app/node_modules ./node_modules
COPY --chown=runner:nodejs . .
COPY --chown=runner:nodejs ./.env.dev ./.env

# Switch to non-root runner
USER runner

# Expose application port
EXPOSE 3000

# Start the application with explicit host binding
CMD ["bun", "run", "start"]
